document.write('<footer class="footer-style1 light-bg-1 pb-0 pt-70">');
document.write('    <div class="container">');
document.write('        <div class="row">');
document.write('            <div class="col-lg-5">');
document.write('                <div class="footer-widget mb-4 mb-lg-5">');
document.write('                    <a href="#" class="site-logo mb-40">');
document.write('                        <img src="./frontend/img/b.svg" class="obj_fit_contain" alt="">');
document.write('                        <span>rixsar</span>');
document.write('                    </a>');
document.write('                    <div class="row mb-4 mb-lg-5">');
document.write('                        <div class="ff-heading">');
document.write('                            <p class="mb-5 me-lg-4">');
document.write('                                A contemporary theme we designed specifically for real estate and property');
document.write('                                showcase');
document.write('                                websites, equipped with every');
document.write('                                option, element and feature your site may need');
document.write('                            </p>');
document.write('                        </div>');
document.write('                        <div class="col-auto">');
document.write('                            <div class="contact-info">');
document.write('                                <p class="info-title">Total Free Customer Care</p>');
document.write('                                <h6 class="info-phone"><a href="tel:+012305094502">+(0) 123 050 945 02</a></h6>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                        <div class="col-auto">');
document.write('                            <div class="contact-info">');
document.write('                                <p class="info-title">Need Live Support?</p>');
document.write('                                <h6 class="info-mail"><a href="mailto:hi@homez.com">hi@homez.com</a></h6>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <div class="social-widget">');
document.write('                        <h6 class="mb-20">Follow us on social media</h6>');
document.write('                        <div class="social-footer">');
document.write('                            <a href="#">');
document.write('                                <i class="fab fa-facebook-f list-inline-item"></i>');
document.write('                            </a>');
document.write('                            <a href="#">');
document.write('                                <i class="fab fa-twitter list-inline-item"></i>');
document.write('                            </a>');
document.write('                            <a href="#">');
document.write('                                <i class="fab fa-instagram list-inline-item"></i>');
document.write('                            </a>');
document.write('                            <a href="#">');
document.write('                                <i class="fab fa-linkedin-in list-inline-item"></i>');
document.write('                            </a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-lg-7">');
document.write('                <div class="mb-4 mb-lg-5">');
document.write('                    <div class="mb-4 mb-lg-5">');
document.write('                        <h6 class="title mb-20">Keep Yourself Up to Date</h6>');
document.write('                        <div class="input_button-group">');
document.write('                            <input type="email" class="form-control" placeholder="Your Email">');
document.write('                            <button type="submit">Subscribe</button>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <div class="row justify-content-between">');
document.write('                        <div class="col-auto">');
document.write('                            <div class="link-style1 mb-3">');
document.write('                                <h6 class="mb-20">Popular Search</h6>');
document.write('                                <ul class="ps-0">');
document.write('                                    <li><a href="#">Apartment for Rent</a></li>');
document.write('                                    <li><a href="#">Apartment Low to Hide</a></li>');
document.write('                                    <li><a href="#">Offices for Buy</a></li>');
document.write('                                    <li><a href="#">Offices for Rent</a></li>');
document.write('                                </ul>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                        <div class="col-auto">');
document.write('                            <div class="link-style1 mb-3">');
document.write('                                <h6 class="mb-20">Quick Links</h6>');
document.write('                                <ul class="ps-0">');
document.write('                                    <li><a href="./term-of-use.html">Terms of Use</a></li>');
document.write('                                    <li><a href="./privacy-policy.html">Privacy Policy</a></li>');
document.write('                                    <li><a href="#">Packages Information</a></li>');
document.write('                                    <li><a href="#">Our Services</a></li>');
document.write('                                    <li><a href="#">Contact Support</a></li>');
document.write('                                    <li><a href="#">FAQs</a></li>');
document.write('                                </ul>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                        <div class="col-auto">');
document.write('                            <div class="link-style1 mb-3">');
document.write('                                <h6 class="mb-20">Discover</h6>');
document.write('                                <ul class="ps-0">');
document.write('                                    <li><a href="#">Miami</a></li>');
document.write('                                    <li><a href="#">Los Angeles</a></li>');
document.write('                                    <li><a href="#">Chicago</a></li>');
document.write('                                    <li><a href="#">New York</a></li>');
document.write('                                </ul>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('    <div class="container border-top py-4">');
document.write('        <div class="row">');
document.write('            <div class="col-sm-6">');
document.write('                <div class="text-center text-lg-start">');
document.write('                    <p class="copyright-text ff-heading mb-0">');
document.write('                        © Brixsar 2024');
document.write('                        <a href="https://themeforest.net/user/ib-themes" target="_blank"');
document.write('                            rel="noopener noreferrer">Brixsar-themes</a> - All rights');
document.write('                        reserved');
document.write('                    </p>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-sm-6">');
document.write('                <div class="text-center text-lg-end">');
document.write('                    <p class="footer-menu ff-heading mb-0">');
document.write('                        <a class="" href="./privacy-policy.html">Privacy</a>');
document.write('                        <a class="" href="./term-of-use.html">Terms</a>');
document.write('                        <a class="" href="#">Sitemap</a>');
document.write('                    </p>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</footer>');