document.write('<header class="header header-light" id="header">');
document.write('    <nav class="navbar container-fluid">');
document.write('        <div class="site-logo-wrap">');
document.write('            <a href="./index.html" class="site-logo">');
document.write('                <img src="./frontend/img/b.svg" class="obj_fit_contain" alt="">');
document.write('                <span>rixsar</span>');
document.write('            </a>');
document.write('        </div>');
document.write('        <div class="menu" id="menu">');
document.write('            <ul class="menu-inner">');
document.write('                <li><a href="./index.html" class="menu_item active">Home</a></li>');
document.write('                <li><a href="./about.html" class="menu_item">About</a></li>');
document.write('                <li><a href="./listing.html" class="menu_item">Sales & Rental</a></li>');
document.write('                <li><a href="./blog.html" class="menu_item">Blog</a></li>');
document.write('                <li><a href="./contact-us.html" class="menu_item">Contact Us</a></li>');
document.write('                <!--This Button will only Show on Mobile View -->');
document.write('                <a href="" class="th-btn th-btn-after gap-3">');
document.write('                    <i class="fa-solid fa-house"></i>');
document.write('                    <span>Add Property</span>');
document.write('                </a>');
document.write('            </ul>');
document.write('        </div>');
document.write('        <div class="nav-action-wrap">');
document.write('            <div class="header-left-link">');
document.write('                <a href="./log-in.html" class="menu_item">');
document.write('                    <img src="./frontend/img/icons/login.svg" alt="">');
document.write('                    <span>Login / Register</span>');
document.write('                </a>');
document.write('                <a href="" class="th-btn th-btn-after gap-3">');
document.write('                    <i class="fa-solid fa-house"></i>');
document.write('                    <span>Add Property</span>');
document.write('                </a>');
document.write('            </div>');
document.write('            <div class="burger" id="burger">');
document.write('                <span class="burger-line"></span>');
document.write('                <span class="burger-line"></span>');
document.write('                <span class="burger-line"></span>');
document.write('            </div>');
document.write('        </div>');
document.write('    </nav>');
document.write('</header>');